### ISSUE TITLE
rt: better blas management

### ISSUE THREAD

**Issue by w23** [w23/xash3d-fwgs#533]
- [x] Do not multiply studio mode vertices by model matrix. Compute vertices in model-local coordinate, and then pass the model matrix to renderer.
- [x] Better BLAS management APIs
- [x] Pre-build static studio model BLASes: #236
- [x] #354 
- [x] #443 
- [x] When studio models manage their blases consciously wrt animations, then global BLAS cache can just go: #350
- [ ] ~~RT material should be decided per-entity/model type, and not discovered later based on traditional render digested pipeline render type:~~ -- will be done separately
  - [ ] #521
  - [ ] #213 
- [x] After studio models BLASes are cached properly, verify and update various BLAS limits: #422 
- [x] Static studio models will fix this particular case of #364
